# api/v1/urls.py

from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

# Import your views from the v1/views folder
from .views import (AppHomeView, GlobalSearchView, AthleteViewSet, ProfileViewSet, 
                    OrganizationViewSet, SchoolViewSet, AchievementViewSet, 
                    StatViewSet, VideoViewSet)

# --- Router Setup for ViewSets ---
# Routers automatically create URLs like /athletes/, /athletes/5/, etc.
router = DefaultRouter()
router.register(r'athletes', AthleteViewSet, basename='athlete')
router.register(r'profiles', ProfileViewSet, basename='profile')
router.register(r'organizations', OrganizationViewSet, basename='organization')
router.register(r'schools', SchoolViewSet, basename='school')
router.register(r'achievements', AchievementViewSet, basename='achievement')
router.register(r'stats', StatViewSet, basename='stat')
router.register(r'videos', VideoViewSet, basename='video')

urlpatterns = [
    # 1. The App Home Endpoint (Custom APIView)
    path('home/', AppHomeView.as_view(), name='app-home'),

    # The dedicated search endpoint
    # Accessible via: /api/search/?q=soccer
    path('search/', GlobalSearchView.as_view(), name='global-search'),

    # 2. The ViewSet Endpoints (generated by router)
    path('', include(router.urls)),
]
