# api/v1/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter

# Import your views from the v1/views folder
from .views import AppHomeView, GlobalSearchView
from .views import AthleteViewSet, ProfileViewSet, OrganizationViewSet, SchoolViewSet

# --- Router Setup for ViewSets ---
# Routers automatically create URLs like /athletes/, /athletes/5/, etc.
router = DefaultRouter()
router.register(r'athletes', AthleteViewSet, basename='athlete')
router.register(r'profiles', ProfileViewSet, basename='profile')
router.register(r'organizations', OrganizationViewSet, basename='organization')
router.register(r'schools', SchoolViewSet, basename='school')

urlpatterns = [
    # 1. The App Home Endpoint (Custom APIView)
    path('home/', AppHomeView.as_view(), name='app-home'),

    # The dedicated search endpoint
    # Accessible via: /api/search/?q=soccer
    path('search/', GlobalSearchView.as_view(), name='global-search'),

    # 2. The ViewSet Endpoints (generated by router)
    path('', include(router.urls)),
]
