# Generated by Django 5.2.9 on 2025-12-30 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='athletes.person')),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
                ('sport', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('graduation_year', models.IntegerField()),
                ('coach_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='organizations.organization')),
            ],
            bases=('athletes.person',),
        ),
    ]
